### ISSUE TITLE
Account Creation

### ISSUE THREAD

**Issue by richardhertzog** [CleanSpeak/cleanspeak-site#4]
Account creation at https://account.cleanspeak.com/account/ is not possible.

Clicking `Create an account` with or without input in the form refreshes the page with mostly 200's and 302's but returns to the same form.

**Comment by robotdan** [comment]
Thanks for reporting this! 

The self service registration link should not have been shown. Fixed!

**Comment by richardhertzog** [comment]
Perhaps this should be updated to reflect where a user can register as well.

https://cleanspeak.com/docs/3.x/tech/tutorials/setup-wizard

**Comment by robotdan** [comment]
The CleanSpeak account is to manage your license primarily, or find the download links if you're self hosting CleanSpeak. 

The setup wizard that you linked to is used to create your first user and setup CleanSpeak. This is separate from an account on https://account.cleanspeak.com.
